/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "anomaly_metadata.h"
#include "tflite-model/tflite_learn_976281_4.h"
#include "tflite-model/tflite_anomaly_976281_5.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_976281_1[] = { "fall_backward", "fall_bending", "fall_forward", "fall_hand", "fall_sideward_left", "fall_sideward_right", "fall_sitting", "fall_syncope", "going_down_stairs", "going_up_stairs", "jump", "lying_down_fs", "run", "sitting_down", "standing_up_fl", "standing_up_fs", "walk" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_976281_3_axes[] = { 0, 1, 2 };
const uint32_t ei_dsp_config_976281_3_axes_size = 3;
ei_dsp_config_spectral_analysis_t ei_dsp_config_976281_3 = {
    3, // uint32_t blockId
    4, // int implementationVersion
    3, // int length of axes
    1.0f, // float scale-axes
    1, // int input-decimation-ratio
    "none", // select filter-type
    3.0f, // float filter-cutoff
    6, // int filter-order
    "FFT", // select analysis-type
    16, // int fft-length
    3, // int spectral-peaks-count
    0.1f, // float spectral-peaks-threshold
    "0.1, 0.5, 1.0, 2.0, 5.0", // string spectral-power-edges
    true, // boolean do-log
    true, // boolean do-fft-overlap
    1, // int wavelet-level
    "db4", // select wavelet
    false // boolean extra-low-freq
};

const float ei_dn_standard_scaler_mean_976281_3[39] = { 5.635680707922803, 0.035145223321301725, -0.0808211526745506, 1.9299076904197998, 2.4238196375576897, 2.191692667566914, 1.8955996854506285, 1.6897543686736187, 1.4782808730665389, 1.4138816762331305, 1.3598168920970184, 1.361145948046185, 1.4143673624141213, 5.668321083261772, 0.03345662027506873, -0.0848288827458157, 1.9252242590430737, 2.41131784999304, 2.1978850877734173, 1.894103366714975, 1.6904709024585864, 1.4913944893901392, 1.4168595576758558, 1.3734673613586061, 1.3759130488789986, 1.3858765872437926, 5.663927352548513, 0.033333774342312654, -0.05300342179867537, 1.9279079463766675, 2.41303096818654, 2.2029913855853125, 1.8882566633469755, 1.688918051623382, 1.5044196138923511, 1.4111775767297783, 1.3735944754841367, 1.3776048896883246, 1.3538548493734064 };
const float ei_dn_standard_scaler_scale_976281_3[39] = { 1.0113747753813658, 1.9244973167773871, 0.7997929205462313, 2.265058257166478, 0.7569009986299499, 4.011529671709127, 3.240988610305004, 2.921655384373345, 3.0030490345284258, 3.183539164536537, 2.971955865490702, 2.892242681853706, 2.6476093887859418, 1.0058574234023931, 1.9550900189312264, 0.8031621056777756, 2.216505412100781, 0.7458485891949636, 3.9991086672554674, 3.250750688204783, 2.89421786401089, 2.9678406637832415, 3.1780504240923966, 2.992865379506058, 2.890744659965086, 2.433376457294389, 1.009615451827778, 1.9102016037157077, 0.7930462127766268, 2.2601491964627853, 0.7548474120760147, 4.038116050910235, 3.1964437896834093, 2.891606547235327, 3.0208686310430566, 3.14401786315502, 2.9893534409411275, 2.8678093161791716, 2.3090236541626177 };
const float ei_dn_standard_scaler_var_976281_3[39] = { 0.9776328014330169, 0.2700010046692812, 1.563309218301134, 0.1949131979158764, 1.7455079997076637, 0.06214124960602239, 0.09520176287137175, 0.11714992711198949, 0.11088560055454096, 0.09866874538056215, 0.11321795040722507, 0.11954475829593517, 0.14265670050069099, 0.9883872834076082, 0.2616173142200624, 1.5502208748579505, 0.20354592296843446, 1.79762316035353, 0.0625278634612765, 0.09463083531694148, 0.11938164541863489, 0.11353214363646458, 0.0990098568956783, 0.11164149280328009, 0.1196686897299738, 0.1688812349280515, 0.9810429532796989, 0.27405743539144684, 1.590021544787213, 0.19576082324482882, 1.7550183395312573, 0.06132568503360021, 0.09787366621224812, 0.1195973622189305, 0.10958126789887566, 0.10116493113894771, 0.11190396318789911, 0.12159044769465581, 0.18756130081881733 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_976281_3 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_976281_3,
    .mean_data_len = 39,
    .scale_data = (float *)ei_dn_standard_scaler_scale_976281_3,
    .scale_data_len = 39,
    .var_data = (float *)ei_dn_standard_scaler_var_976281_3,
    .var_data_len = 39
};
ei_data_normalization_t ei_data_normalization_config_976281_3 = {
    (void *) &ei_data_normalization_standard_scaler_config_976281_3, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_976281_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_976281_1[ei_dsp_blocks_976281_1_size] = {
    { // DSP block 3
        3,
        39, // output size
        &extract_spectral_analysis_features, // DSP function pointer
        (void*)&ei_dsp_config_976281_3, // pointer to config struct
        ei_dsp_config_976281_3_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_976281_3_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_976281_3, // data normalization config
    }
};
const ei_config_tflite_graph_t ei_config_graph_976281_4 = {
    .implementation_version = 1,
    .model = tflite_learn_976281_4,
    .model_size = tflite_learn_976281_4_len,
    .arena_size = tflite_learn_976281_4_arena_size
};

const ei_config_tflite_graph_t ei_config_graph_976281_5 = {
    .implementation_version = 1,
    .model = tflite_anomaly_976281_5,
    .model_size = tflite_anomaly_976281_5_len,
    .arena_size = tflite_anomaly_976281_5_arena_size
};

const uint8_t ei_output_tensors_indices_976281_4[1] = { 0 };
const uint8_t ei_output_tensors_size_976281_4 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_976281_4 = {
    .implementation_version = 1,
    .block_id = 4,
    .output_tensors_indices = ei_output_tensors_indices_976281_4,
    .output_tensors_size = ei_output_tensors_size_976281_4,
    .quantized = 0,
    .compiled = 0,
    .graph_config = (void*)&ei_config_graph_976281_4,
    .dequantize_output = 0,
};

ei_learning_block_config_anomaly_gmm_t ei_learning_block_config_976281_5 = {
    .implementation_version = 1,
    .block_id = 5,
    .anom_axis = ei_classifier_anom_axes_976281_5,
    .anom_axes_size = 4,
    .graph_config = (void*)&ei_config_graph_976281_5
};

const uint8_t ei_learning_blocks_976281_1_size = 2;
const uint32_t ei_learning_block_976281_4_inputs[1] = { 3 };
const uint8_t ei_learning_block_976281_4_inputs_size = 1;
const uint32_t ei_learning_block_976281_5_inputs[1] = { 3 };
const uint8_t ei_learning_block_976281_5_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_976281_1[ei_learning_blocks_976281_1_size] = {
    {
        4,
        &run_nn_inference,
        (void*)&ei_learning_block_config_976281_4,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_976281_4_inputs,
        ei_learning_block_976281_4_inputs_size,
    },
    {
        5,
        &run_gmm_anomaly,
        (void*)&ei_learning_block_config_976281_5,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_976281_5_inputs,
        ei_learning_block_976281_5_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_976281_1_size = 2;
const ei_postprocessing_block_t ei_postprocessing_blocks_976281_1[ei_postprocessing_blocks_976281_1_size] = {
    {
        .block_id = 4,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 4
    },
    {
        .block_id = 5,
        .type = EI_CLASSIFIER_MODE_ANOMALY_GMM,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_anomaly,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 5
    },
};

const uint8_t freeform_outputs_976281_1_size = 0;

uint32_t *freeform_outputs_976281_1 = nullptr;

const ei_impulse_t impulse_976281_1 = {
    .project_id = 976281,
    .project_owner = "Hectorgh24",
    .project_name = "Deteccion-caidas-17-clases",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 39,
    .raw_sample_count = 100,
    .raw_samples_per_frame = 3,
    .dsp_input_frame_size = 100 * 3,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 20,
    .frequency = 50,

    .dsp_blocks_size = ei_dsp_blocks_976281_1_size,
    .dsp_blocks = ei_dsp_blocks_976281_1,

    .learning_blocks_size = ei_learning_blocks_976281_1_size,
    .learning_blocks = ei_learning_blocks_976281_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_976281_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_976281_1,

    .output_tensors_size = 2,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_ACCELEROMETER,
    .fusion_string = "accX + accY + accZ",
    .slice_size = (100/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_GMM,
    .label_count = 17,
    .categories = ei_classifier_inferencing_categories_976281_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_976281_1_size,
    .freeform_outputs = freeform_outputs_976281_1
};

ei_impulse_handle_t impulse_handle_976281_1 = ei_impulse_handle_t( &impulse_976281_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_976281_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_976281_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_976281_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_976281_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
